name: McCore
version: 1.4.1
main: me.crazybanana.mccore.McCore
api-version: 1.16
authors: [CrazyBanana]
description: This is the core plugin for MC
commands:
  mcorereload:
    description: Use this command to reload the plugin
    aliases: [mcreload, mcrl]
  ban:
    description: Use this command to ban people from the server
    aliases: [mcban, mcoreban]
  ipban:
    description: Use this command to ip ban people from the server
    aliases: [mcipban, banip, mcbanip]
  mute:
    description: Use this command to mute people on the server
    aliases: [mcmute]
  announce:
    description: Use this command to make announcements throughout the server
    aliases: [ac, mcannounce, mcan, broadcast, bc, mcbroadcast, mcbc]